framework:
    default_locale: cs
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                locales: ['cs', 'en']
                domains: ['homepage']